CREATE TABLE Product(
    ID INT UNSIGNED UNIQUE,
    PRODUCT_NAME VARCHAR(100),
    SUP_ID INT UNSIGNED UNIQUE,
    CAT_ID INT UNSIGNED UNIQUE,
    UNIT INT UNSIGNED,
    UNIT_PRICE INT UNSIGNED,
    TOTAL INT UNSIGNED
)

SELECT * FROM PRODUCT
INSERT INTO PRODUCT(ID, PRODUCT_NAME, SUP_ID, CAT_ID, UNIT, UNIT_PRICE, TOTAL) VALUE(3, 'Banana', 56, 47, 5, 6, 50)
UPDATE PRODUCT SET PRODUCT_NAME = 'Apple' WHERE ID = 3;

SELECT MIN(TOTAL) AS SMALLESTPRCE FROM PRODUCT;
SELECT MAX(TOTAL) AS LARGESTPRCE FROM PRODUCT;
SELECT AVG(TOTAL) FROM PRODUCT;
SELECT SUM(TOTAL) FROM PRODUCT;