-- CREATE DATABASE MYTESTDB
-- USE MYTESTDB

-- CREATE TABLE MYTESTTABLE(
--     Id INT UNSIGNED UNIQUE,
--     USER_NAME VARCHAR(150),
--     FATHER_NAME VARCHAR(150),
--     MOTHER_NAME VARCHAR(150),
--     EMAIL VARCHAR(100),
--     PHONE VARCHAR(100)
-- )

-- SELECT * FROM MYTESTTABLE;
-- INSERT INTO MYTESTTABLE(Id, User_NAME, FATHER_NAME, MOTHER_NAME, EMAIL, PHONE) VALUE(1, 'Jakir', 'Humaion Ali', 'Banu Begum', 'jakir.ruet.bd@gmail.com', '+8801788916805');
-- INSERT INTO MYTESTTABLE(Id, User_NAME, FATHER_NAME, MOTHER_NAME, EMAIL, PHONE) VALUE(2, 'Jasim', 'Ali Ahmed', 'Sarah Begum', 'jasim.ruet.bd@gmail.com', '+8801788916806');
