DROP TABLE TABLE_ONE
CREATE TABLE TABLE_ONE(
    ORDER_ID INT UNSIGNED UNIQUE,
    CUS_ID INT UNSIGNED UNIQUE,
    CUS_NAME VARCHAR(100),
    ORDER_DATE DATE
)

INSERT INTO TABLE_ONE(ORDER_ID, CUS_ID, CUS_NAME, ORDER_DATE) VALUE(23, 45, 'Jakir', '10-17-2021 15:40:10')

CREATE TABLE TABLE_TWO(
    CUS_ID INT UNSIGNED UNIQUE,
    EMAIL VARCHAR(120),
    CONTACT VARCHAR(100),
    COUNTRY VARCHAR(120)
)

SELECT TABLE_ONE.ORDER_ID, TABLE_TWO.CUS_ID, TABLE_ONE.CUS_NAME, TABLE_TWO.CONTACT
FROM TABLE_ONE
INNER JOIN TABLE_TWO ON TABLE_ONE.CUS_ID = TABLE_TWO.CUS_ID