CREATE TABLE MYOPERATORS(
    ID INT UNSIGNED UNIQUE,
    USER_NAME VARCHAR(100),
    SCHOOL_NAME VARCHAR(250),
    EMAIL VARCHAR(120),
    CONTACT VARCHAR(100)
)

SELECT * FROM MYOPERATORS
INSERT INTO MYOPERATORS(ID, USER_NAME, SCHOOL_NAME, EMAIL, CONTACT) VALUE(5, 'Rony', 'DA High School', 'rony@gmail.com', 535545)

SELECT * FROM MYOPERATORS WHERE USER_NAME = 'Jakir' AND CONTACT='545435'
SELECT * FROM MYOPERATORS WHERE USER_NAME = 'Jakir' OR CONTACT='535545'
SELECT * FROM MYOPERATORS WHERE NOT USER_NAME = 'Jakir'

-- Combining
SELECT * FROM MYOPERATORS WHERE USER_NAME = 'Jakir' AND (SCHOOL_NAME = 'MHA High School' OR EMAIL = 'rony@gmail.com' OR EMAIL = 'jabber@gmail.com')

-- Order
SELECT * FROM MYOPERATORS ORDER BY USER_NAME ASC
SELECT * FROM MYOPERATORS ORDER BY USER_NAME DESC

-- Not
SELECT * FROM MYOPERATORS WHERE NOT USER_NAME = 'Jakir'

-- In
SELECT * FROM MYOPERATORS WHERE USER_NAME IN ('Jakir', 'Rony', 'Jabbar')
SELECT * FROM MYOPERATORS WHERE USER_NAME NOT IN ('Jakir', 'Rony', 'Jabbar')

-- Between
SELECT * FROM MYOPERATORS WHERE CONTACT BETWEEN 40000 AND 50000

-- In & Between
SELECT * FROM MYOPERATORS WHERE CONTACT BETWEEN 30000 AND 100000 AND EMAIL NOT IN ('jakir@gmail.com')