CREATE TABLE MYOPERATORS(
    ID INT UNSIGNED UNIQUE,
    USER_NAME VARCHAR(100),
    SCHOOL_NAME VARCHAR(250),
    EMAIL VARCHAR(120),
    CONTACT VARCHAR(100)
)

SELECT * FROM MYOPERATORS
INSERT INTO MYOPERATORS(ID, USER_NAME, SCHOOL_NAME, EMAIL, CONTACT) VALUE(5, 'Rony', 'DA High School', 'rony@gmail.com', 535545)

SELECT * FROM MYOPERATORS WHERE USER_NAME = 'Jakir' AND CONTACT='545435'
SELECT * FROM MYOPERATORS WHERE USER_NAME = 'Jakir' OR CONTACT='535545'
SELECT * FROM MYOPERATORS WHERE NOT USER_NAME = 'Jakir'

SELECT * FROM MYOPERATORS WHERE USER_NAME = 'Jakir' AND (SCHOOL_NAME = 'MHA High School' OR EMAIL = 'rony@gmail.com' OR EMAIL = 'jabber@gmail.com')